ALTER TABLE "Content" ADD COLUMN "audioId" TEXT;
ALTER TABLE "Content" ADD COLUMN "audioTitle" TEXT;
ALTER TABLE "Content" ADD COLUMN "audioArtist" TEXT;
ALTER TABLE "Content" ADD COLUMN "audioVolume" INTEGER NOT NULL DEFAULT 100;
ALTER TABLE "Content" ADD COLUMN "videoVolume" INTEGER NOT NULL DEFAULT 100;
